# Generated by Django 3.1.6 on 2021-11-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basenodedegree',
            unique_together={('from_basenode', 'to_basenode')},
        ),
    ]
